FROM golang:1.20-alpine as buildbase

WORKDIR /go/src/github.com/hyle-team/bridgeless-core/v12
COPY vendor .
COPY . .

RUN apk add build-base

ENV GO111MODULE="on"
ENV CGO_ENABLED=1
ENV GOOS="linux"

RUN go build -o /usr/local/bin/bridgeless-core github.com/hyle-team/bridgeless-core/v12/cmd/bridgeless-cored

###

FROM alpine:3.9

RUN apk add --no-cache ca-certificates

COPY --from=buildbase /usr/local/bin/bridgeless-core /usr/local/bin/bridgeless-core

ENTRYPOINT ["bridgeless-core"]